irvanrizkin/trafo-monitor

app/Http/Controllers/TrafoV2Controller.php
package-lock.json
package.json
resources/js/Components/Detail/ParameterInfoCard.tsx
resources/js/Pages/TrafoV2/Detail.tsx
resources/js/types/index.d.ts

Some code I edited ✌️ 
[x] Edit props ParameterInfoCard
[x] Add marker on maps
[x] Link button to chart

[UPDATE]: Link button to chart

---

resources/js/Pages/Trafo/DetailV1.tsx

- add and change dropdown value at detail
- [TM-1](https://irvanrizkin.atlassian.net/browse/TM-1)

[TM-1] [FE] [NEW] Add & Change Dropdown Value at Detail

---

resources/js/Components/Trafo/TrafoCard.tsx

- add location and createdAt on dashboard card
- [TM-2](https://irvanrizkin.atlassian.net/browse/TM-2)

[TM-2] [FE] [NEW] Modify Card at Dashboard

---

resources/js/Pages/Chart/ChartPKA.tsx
resources/js/Pages/Chart/ChartPQSPF.tsx
resources/js/Pages/Chart/ChartVIF.tsx
resources/js/Pages/DashboardV2.tsx
resources/js/helpers/generator/chart-generator.ts
resources/js/helpers/generator/dataset-generator.ts

- change all color to material ui and abstracting chart generator
- [TM-9](https://irvanrizkin.atlassian.net/browse/TM-9)

[TM-9] [FE] [NEW] Change Chart Line Color Match Appbar

---

app/Http/Controllers/ChartController.php
app/Http/Controllers/MetricController.php
app/Models/THDVoltage.php
database/migrations/2024_09_10_134449_create_t_h_d_voltages_table.php
resources/js/Pages/Chart/ChartTHDIHD.tsx
resources/js/Pages/Chart/ChartVIF.tsx
resources/js/Pages/Metric/MetricTHDIHD.tsx
resources/js/helpers/generator/chart-generator.ts
resources/js/types/chart.d.ts
resources/js/types/metric.d.ts

- add voltage and current at THD metric
- add voltage and current at THD chart
- [TM-19](https://irvanrizkin.atlassian.net/browse/TM-19)

[TM-19] [FE] [NEW] Add Voltage and Current on THD with RST

---

app/Http/Controllers/ChartController.php
app/Http/Controllers/MetricController.php
resources/js/Pages/Chart/ChartTPO.tsx
resources/js/Pages/Metric/MetricIHD.tsx
resources/js/Pages/Metric/MetricTPO.tsx
resources/js/Pages/Trafo/DetailV1.tsx
resources/js/types/chart.d.ts
resources/js/types/metric.d.ts
routes/web.php

- add metric placeholder for TPO
- add chart placeholder for TPO
- fix ordo duplicate H15 at MetricIHD
- [TM-13](https://irvanrizkin.atlassian.net/browse/TM-13)

[TM-13] [FE] [NEW] Chart & Table Empty Placeholder for Data 5

---

resources/js/Pages/Chart/ChartIHD.tsx
resources/js/Pages/Chart/ChartPKA.tsx
resources/js/Pages/Chart/ChartPQSPF.tsx
resources/js/Pages/Chart/ChartTHDIHD.tsx
resources/js/Pages/Chart/ChartTPO.tsx
resources/js/Pages/Chart/ChartVIF.tsx
resources/js/Pages/Metric/MetricPQSPF.tsx
resources/js/Pages/Metric/MetricTPO.tsx
resources/js/Pages/Metric/MetricVIF.tsx

- add unit on metric table
- add unit on chart
- [TM-10](https://irvanrizkin.atlassian.net/browse/TM-10)
- [TM-12](https://irvanrizkin.atlassian.net/browse/TM-12)

[TM-10] [TM-12] [FE] [NEW] Add Unit on Table

---

resources/js/Components/Metric/GaugeGroup.tsx

- added color gauge by threshold
- [TM-4](https://irvanrizkin.atlassian.net/browse/TM-4)

[TM-4] [FE] [NEW] Gauge Color Indicator

---

app/Http/Controllers/MetricController.php
resources/js/Components/Metric/TimeNavigator.tsx
resources/js/Pages/Metric/MetricIHD.tsx
routes/api.php

- add time navigation at metric IHD
- [TM-7](https://irvanrizkin.atlassian.net/browse/TM-7)

[TM-7] [FE] [NEW] Add Time Widget & Arrow for Time Nav at IHD

---

app/Http/Controllers/ChartController.php
resources/js/Pages/Chart/ChartPKA.tsx
resources/js/Pages/Chart/ChartPQSPF.tsx
resources/js/Pages/Chart/ChartTHDIHD.tsx
resources/js/Pages/Chart/ChartVIF.tsx
resources/js/helpers/converter/date-time.ts
resources/js/helpers/generator/chart-generator.ts
resources/js/types/chart.d.ts

- change vif chart to hour
- change pqspf chart to hour
- change thd chart to hour
- change pka chart to hour
- [TM-5](https://irvanrizkin.atlassian.net/browse/TM-5)

[TM-5] [FE] [NEW] Change Chart to Last Hour and Group 5 min

---

resources/js/Components/Chart/AggregationRST.tsx
resources/js/Components/Chart/AggregationRSTIN.tsx
resources/js/Components/Chart/AggregationRSTOnly.tsx
resources/js/Components/Chart/AggregationSingle.tsx
resources/js/Pages/Chart/ChartIHD.tsx
resources/js/Pages/Chart/ChartPKA.tsx
resources/js/Pages/Chart/ChartPQSPF.tsx
resources/js/Pages/Chart/ChartTHDIHD.tsx
resources/js/Pages/Chart/ChartTPO.tsx
resources/js/Pages/Chart/ChartVIF.tsx
resources/js/helpers/analysis/calculate-metric.ts
resources/js/types/component.d.ts

- chart vif aggregation table
- chart pqspf aggregation table
- chart thd aggregation table
- chart pka aggregation table
- chart tpo aggregation table
- change chart vif aggregation to use helper + add return if array empty
- chart ihd aggregation table + fix styling
- [TM-8](https://irvanrizkin.atlassian.net/browse/TM-8)

[TM-8] [FE] [NEW] Add Agregation for each R S T IN

---

resources/js/Components/Map/CustomMarker.tsx
resources/js/Components/Map/GoogleMap.tsx
resources/js/Pages/Chart/ChartIHD.tsx
resources/js/Pages/Chart/ChartPKA.tsx
resources/js/Pages/Chart/ChartPQSPF.tsx
resources/js/Pages/Chart/ChartTHDIHD.tsx
resources/js/Pages/Chart/ChartTPO.tsx
resources/js/Pages/Chart/ChartVIF.tsx
resources/js/Pages/Dashboard.tsx
resources/js/Pages/Trafo/DetailV1.tsx
resources/js/helpers/map/default-center.ts
resources/js/types/component.d.ts

- added label at map pinpoint on dashboard
- added default center function to comply with DRY
- change gmaps at chart to component
- [TM-3](https://irvanrizkin.atlassian.net/browse/TM-3)

[TM-3] [FE] [NEW] Add Trafo Name at Pinpoint

---

app/Http/Controllers/ChartController.php

- change last one hour to last 12 data
- [TM-21](https://irvanrizkin.atlassian.net/browse/TM-21)

[TM-12] [BE] [NEW] Change to Get Last 12 Data

---

resources/js/helpers/generator/chart-generator.ts
resources/js/helpers/generator/dataset-generator.ts

- change fill color for line chart legend
- [TM-22](https://irvanrizkin.atlassian.net/browse/TM-22)

[TM-22] [FE] [NEW] Change Legend Color to Fill like THD Bar

---

resources/js/Pages/Chart/ChartPQSPF.tsx
resources/js/Pages/Chart/ChartTPO.tsx
resources/js/Pages/Chart/ChartVIF.tsx
resources/js/Pages/Metric/MetricPQSPF.tsx
resources/js/Pages/Metric/MetricTPO.tsx
resources/js/Pages/Metric/MetricVIF.tsx

- change unit at vif, pqspf, tpo
- [TM-24](https://irvanrizkin.atlassian.net/browse/TM-24)

[TM-24] [FE] [NEW] Change Unit on VIF, PQSPF, TPO

---

resources/js/Pages/Chart/ChartTPO.tsx
resources/js/Pages/Metric/MetricTPO.tsx

- change temperature to oil temperature
- [TM-26](https://irvanrizkin.atlassian.net/browse/TM-26)

[TM-26] [FE] [NEW] Change to Oil Temperature

---

resources/js/Components/Chart/AggregationRST.tsx
resources/js/Components/Chart/AggregationRSTIN.tsx
resources/js/Components/Chart/AggregationRSTOnly.tsx
resources/js/Components/Chart/AggregationSingle.tsx

- change aggregation table to dense table
- [TM-20](https://irvanrizkin.atlassian.net/browse/TM-20)

[TM-20] [FE] [NEW] Change to Dense Table MUI

---

resources/js/Components/Chart/AggregationRST.tsx
resources/js/Components/Chart/AggregationRSTIN.tsx
resources/js/Components/Chart/AggregationSingle.tsx
resources/js/Pages/Chart/ChartPKA.tsx
resources/js/Pages/Chart/ChartPQSPF.tsx
resources/js/Pages/Chart/ChartTHDIHD.tsx
resources/js/Pages/Chart/ChartTPO.tsx
resources/js/Pages/Chart/ChartVIF.tsx
resources/js/helpers/analysis/get-createdat.ts
resources/js/types/component.d.ts

- added max min time at chart vif
- added max min time at chart pqspf
- added max min time at chart thd
- added max min time at chart pka
- added max min time at chart tpo
- [TM-23](https://irvanrizkin.atlassian.net/browse/TM-23)

[TM-23] [FE] [NEW] Add Time When Data Max and Min

---

app/Http/Controllers/Metric/MetricMQTTController.php
app/Http/Controllers/TrafoController.php
app/Models/DateGroup.php
app/Models/Frequency.php
app/Models/OilLevel.php
app/Models/Pressure.php
app/Models/Temperature.php
database/migrations/2024_09_26_111454_create_date_groups_table.php
resources/js/Pages/Trafo/DetailV1.tsx
resources/js/types/index.d.ts
routes/api.php

- added post endpoint for mqtt
- change dategroup method using separate table
- [TM-29](https://irvanrizkin.atlassian.net/browse/TM-29)

[TM-29] [BE] [NEW] Create POST to Receive Metric

---

app/Http/Controllers/Chart/ChartPKAController.php
app/Http/Controllers/Chart/ChartPQSPFController.php
app/Http/Controllers/Chart/ChartTHDController.php
app/Http/Controllers/Chart/ChartTPOController.php
app/Http/Controllers/Chart/ChartVIFController.php
app/Http/Controllers/ChartController.php
app/Http/Controllers/Metric/MetricMQTTController.php
app/Models/Current.php
app/Models/THDCurrent.php
app/Models/THDVoltage.php
app/Models/Voltage.php
resources/js/Components/Shared/ButtonEndHref.tsx
resources/js/Pages/Chart/ChartIHD.tsx
resources/js/Pages/Chart/ChartPKA.tsx
resources/js/Pages/Chart/ChartPQSPF.tsx
resources/js/Pages/Chart/ChartTHDIHD.tsx
resources/js/Pages/Chart/ChartTPO.tsx
resources/js/Pages/Chart/ChartVIF.tsx
resources/js/Pages/Metric/MetricIHD.tsx
resources/js/Pages/Metric/MetricPKA.tsx
resources/js/Pages/Metric/MetricPQSPF.tsx
resources/js/Pages/Metric/MetricTHDIHD.tsx
resources/js/Pages/Metric/MetricTPO.tsx
resources/js/Pages/Metric/MetricVIF.tsx
resources/js/Pages/Trafo/DetailV1.tsx
resources/js/types/chart.d.ts
routes/web.php

- add refresh button
- fix reversed chart, latest should be at end
- remote date on chart route
- use previous value for other value
- [TM-34](https://irvanrizkin.atlassian.net/browse/TM-34)

[TM-34] [BE] [NEW] Add Stepped Line due to Separate MQTT
